### ISSUE TITLE
video上传与image和file上传处理不一致，但是service.config.js中需要配置的方法却是一样的。配置无效

### ISSUE THREAD

**Issue by wuhanligong110** [notadd/neditor#101]
![image](https://user-images.githubusercontent.com/5670107/50382356-57f6b780-06d8-11e9-9737-42ff1c1e0298.png)

![image](https://user-images.githubusercontent.com/5670107/50382361-67760080-06d8-11e9-82ce-f685b5e960e6.png)

**Comment by caixinning** [comment]
遇到同样的问题，在尝试修改video.js

**Comment by zuohuadong** [comment]
> 遇到同样的问题，在尝试修改video.js

欢迎提交PR

**Comment by Tian-Hun** [comment]
service配置无效? @wuhanligong110

**Comment by wuhanligong110** [comment]
> service配置无效? @wuhanligong110

service配置中video相关的几个函数根本没被调用

**Comment by Tian-Hun** [comment]
> > service配置无效? @wuhanligong110
> 
> service配置中video相关的几个函数根本没被调用

这是不可能出现的问题，service 确定引入了？
