### ISSUE TITLE
上传图片的弹框太高了。嵌套在iframe里会造成确定按钮被遮挡，无法上传。

### ISSUE THREAD

**Issue by jeesun** [notadd/neditor#106]
上传图片的弹框太高了。嵌套在iframe里会造成确定按钮被遮挡，无法上传。

**Comment by zuohuadong** [comment]
由于项目进度问题，年前暂无时间解决BUG 。可以先自行排查，遇到问题可以在此 回复，欢迎提交PR 。

**Comment by jeesun** [comment]
自己找到了样式，做了修改。但最终还是选择不放iframe里了。
