### ISSUE TITLE
单文件上传在配置怎么被注释了？暂时不支持吗？

### ISSUE THREAD

**Issue by jackiewillen** [notadd/neditor#118]
单文件上传在neditor.config.js中被注释。
![image](https://user-images.githubusercontent.com/7625197/55528266-cd5a2700-56ce-11e9-87dc-fe21c220bc30.png)

**Comment by zuohuadong** [comment]
单文件那个有BUG ，暂时不维护，请直接用多文件上传

**Comment by jackiewillen** [comment]
> 单文件那个有BUG ，暂时不维护，请直接用多文件上传

谢谢
