### ISSUE TITLE
更新到1.5.1后，simpleupload，

### ISSUE THREAD

**Issue by yangmail2002** [notadd/neditor#12]
更新到1.5.1后，simpleupload ，使用Google Chrome 60.0.31127还是很慢，
使用modal,点击全屏后，显示不出来。

**Comment by zuohuadong** [comment]
有截图和环境说明么？

**Comment by TianYouH** [comment]
我也碰见这种问题啦，
是在谷歌浏览器，Vue环境。使用modal窗口，点击全屏后只剩下个黑蒙版

**Comment by zuohuadong** [comment]
我们内部在使用的vue 正常...
