### ISSUE TITLE
如何禁止editor自动移除code标签

### ISSUE THREAD

**Issue by vnoder** [notadd/neditor#13]
过滤白名单中有code标签，在使用的过程中pre 标签下的 code标签还是会被自动移除

例如
```
<pre><code>var a = 0;</code></pre>
```
被替换成

```
<pre>var a = 0;</pre>
```

**Comment by zuohuadong** [comment]
过滤白名单你是在哪里加的？添加了什么内容，格式正确吗？ 能否截个图

**Comment by vnoder** [comment]
白名单是在neditor.config.js里配置的。原因找到了，是 百度编辑器的 `ueditor/_src/plugins/insertcode.js` 插件的问题。

**Comment by vnoder** [comment]
![image](https://user-images.githubusercontent.com/12530526/30845377-b216482a-a2c5-11e7-9218-4e04b75ae273.png)
insertcode.js 添加的inputRule 把 `pre` 下的标签移除了

**Comment by zuohuadong** [comment]
好的
