### ISSUE TITLE
开启远程图片抓取，粘贴进入富文本的图片没有本地化，是怎么回事呢？

### ISSUE THREAD

**Issue by Slp-slp** [notadd/neditor#130]
开启远程图片抓取，粘贴进入富文本的图片没有本地化，是怎么回事呢？

**Comment by zuohuadong** [comment]
先配置好 service

**Comment by Slp-slp** [comment]
service已配置好

**Comment by Tfz1024** [comment]
远程抓取图片本地化偶尔成功偶尔失败，清除浏览器缓存之后成功率大些，这个问题我看了好久其实是抓取成功了的，但是就是没有替换掉，不知道哪里出了问题

**Comment by shaodushu** [comment]
@Tfz1024 遇到同样的问题，请问解决了没有

**Comment by Tfz1024** [comment]
要替换成自己的服务器的地址，打断点慢慢调试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shaodushu"<notifications@github.com&gt;; 
发送时间: 2019年12月17日(星期二) 下午2:51
收件人: "notadd/neditor"<neditor@noreply.github.com&gt;; 
抄送: "Jane"<1032861834@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [notadd/neditor] 开启远程图片抓取，粘贴进入富文本的图片没有本地化，是怎么回事呢？ (#130)




@Tfz1024 遇到同样的问题，请问解决了没有
