### ISSUE TITLE
图片转存灰色不可点

### ISSUE THREAD

**Issue by zhangliang2008** [notadd/neditor#153]
从word复制打数据带图片的,neditor图片转存灰色不可以点,UEditor是可以的
![ueditor](http://img.zgylt.com/Upload/20190615/8104b0b9_0102_4e2d_b8ec_e1cb94732f33.png)
![neditor](http://img.zgylt.com/Upload/20190615/d37a18e1_fdd0_47c9_a0ea_d8d5d0653536.png)

**Comment by zuohuadong** [comment]
demo 站没有配置上传~
