### ISSUE TITLE
上传图片如何使用配置headers？需要jwt认证

### ISSUE THREAD

**Issue by mvpwar** [notadd/neditor#156]
看到neditor.service.js有个setFormData方法有涉及到headers，但不知道怎么使用

**Comment by Yinyihang857** [comment]
我也在想这个问题呢老哥解决没？

**Comment by lam0114** [comment]
> 直接data.xxxx= xxx;header.token = 'xxxxx';
> 可以直接修改对象。里面的数据是引用的
> https://github.com/notadd/neditor/issues/169#issuecomment-568871949
