### ISSUE TITLE
关于编辑器内容乱跳的问题

### ISSUE THREAD

**Issue by feiquan666** [notadd/neditor#158]
![image](https://user-images.githubusercontent.com/42441073/61956942-bf6b4180-aff0-11e9-939f-49c145835427.png)
当往下拉一段距离后就会产生一个和编辑器等宽，高600px的空div
![image](https://user-images.githubusercontent.com/42441073/61957063-fe00fc00-aff0-11e9-9f2e-fe1cbd819349.png)
![image](https://user-images.githubusercontent.com/42441073/61957097-1113cc00-aff1-11e9-8ce9-f6d247295de5.png)

**Comment by zuohuadong** [comment]
iframe 引的吗

**Comment by feiquan666** [comment]
不是

**Comment by haijun568** [comment]
复议，这个问题你们官方的demo就可以发现，在填入内容的是否滚动可以很明显的看出有空白div的出现。

**Comment by eddy8** [comment]
autoFloatEnabled 设置为 false 试试

**Comment by haijun568** [comment]
> autoFloatEnabled 设置为 false 试试

设置这个的确好了，只有小屏幕高度滚动时才会出现，这个滚动编辑区锁定也可以不用。
