### ISSUE TITLE
单图片上传按钮是灰色不可用的

### ISSUE THREAD

**Issue by chegod** [notadd/neditor#159]
## 问题
1. 单图片上传按钮无法使用：
![image](https://user-images.githubusercontent.com/37540452/64004146-4788bd80-cb40-11e9-8461-68ad67ca40ce.png)
2. `videoUploadService`配置了`videoSrcField`后是没用的，还是`url`
![image](https://user-images.githubusercontent.com/37540452/64005560-3c835c80-cb43-11e9-9f3e-f0be98edaca9.png)

感谢作者的开源，希望能解决一下这些问题。

## 尝试寻找原因

`neditor.all.js`中的`simpleupload.js`
![image](https://user-images.githubusercontent.com/37540452/64005078-2e810c00-cb42-11e9-9d02-136332276461.png)
就是`simpleupload`时需要向后端请求一次配置，但是`loadServerConfig`被注释掉了，所以按钮不可用，虽然改了一下可以使用了，但是无法在`neditor.service.js`中进行配置。

**Comment by Tian-Hun** [comment]
单图上传功能已取消
