### ISSUE TITLE
恕我直言，你们的换行符居然是CRLF。。。

### ISSUE THREAD

**Issue by niefufeng** [notadd/neditor#16]
当然咯，对功能没啥影响，只是每次加入`git`的时候，都会出现一大堆类似：`warning: CRLF will be replaced by LF in public/plugins/neditor/neditor.all.js`的提醒

**Comment by twilroad** [comment]
你是在windows下操作的吧？windows下git在checkout的时候会自动把换行符转为crlf。

**Comment by niefufeng** [comment]
我是在`Linux`下操作的啊，提示说的是`CRLF`被`LF`替换啊

**Comment by zuohuadong** [comment]
@twilroad
