### ISSUE TITLE
远程抓取图片报错

### ISSUE THREAD

**Issue by baiyuxiong** [notadd/neditor#170]
1. 在官网 demo 里：https://demo.neditor.notadd.com/试了不行：
![image](https://user-images.githubusercontent.com/230689/71225654-31338700-2314-11ea-8eb8-6406b5399fd4.png)
网络数据包看起来也不对：
![image](https://user-images.githubusercontent.com/230689/71225675-45778400-2314-11ea-97b9-8451ebce50de.png)
2. 在我的代码里测试，请求参数同样不正确，同时上传接口返回没有带 list 参数：
![image](https://user-images.githubusercontent.com/230689/71226231-2aa60f00-2316-11ea-9dfc-14ca12179007.png)
导致下面的 for循环取 list 时报错：
![image](https://user-images.githubusercontent.com/230689/71226278-4f9a8200-2316-11ea-9a26-8fe1609b836f.png)
3. neditor.service.js里UE.Editor.prototype.getActionUrl 参数的 action 传值是 undefined

问题：
1. 为什么请求接口的参数不正确？
2. 不知道这个 list 需要返回什么东西？

**Comment by zuohuadong** [comment]
demo 没有配置上传
