### ISSUE TITLE
增加node的编译版本

### ISSUE THREAD

**Issue by yuu2lee4** [notadd/neditor#18]
希望增加node的编译版本

**Comment by zuohuadong** [comment]
会在下个版本考虑~ 主要还是没会node 的童鞋

**Comment by yuu2lee4** [comment]
加油 CKEditor5都有npm包了

**Comment by zuohuadong** [comment]
团队对node 不熟，要是有人能根据 https://github.com/netpi/ueditor 进行移植的话，欢迎给我们提交PR～

**Comment by twilroad** [comment]
@yuu2lee4 你说的node包，只是一个npm的package，还是？

**Comment by yuu2lee4** [comment]
@twilroad  对 npm的package，分为两方面，一个是前端工程里要用到的包，一个是后端node的包(能在express、koa这些框架里引入使用的)

**Comment by yuu2lee4** [comment]
向这个学习 http://www.wangeditor.com/ 前端的npm包 和 详尽的图片接口文档

**Comment by zuohuadong** [comment]
@yuu2lee4  2.0 移除所有后端语言，纯ajax 提交，预计这周发布～

**Comment by zuohuadong** [comment]
已经发布。。。
