### ISSUE TITLE
编辑器：滚动页面出现大片空白

### ISSUE THREAD

**Issue by icebay** [notadd/neditor#19]
在新增了2图片后，大概是占满了输入窗口的全部。往下滚动，会出现很长的空白 div 标签。
大概跟编辑器的自动高度有关？

**Comment by zuohuadong** [comment]
在核实

**Comment by zuohuadong** [comment]
暂时还没有找到办法解决

**Comment by zuohuadong** [comment]
开发在测试中没有复现此情况，请问有截图么

**Comment by ChiaJune** [comment]
我也遇到这样的问题，id为**edui1_iframeholder**的div高度计算有问题，变得很大，导致出现很多空白，如下图：
![2.png](https://i.loli.net/2018/03/01/5a978fcfa817c.png)

**Comment by Tian-Hun** [comment]
@IceBay @ChiaJune 未复现 请提供相关前端配置项

**Comment by vanishcode** [comment]
```js
// initialFrameHeight: 700, 注释掉高度
autoHeightEnabled: true,
```
