### ISSUE TITLE
对齐效果有bug

### ISSUE THREAD

**Issue by ucando** [notadd/neditor#2]
文字或图片改变对齐方式后, 图标没有进行相应的变化

比如一开始是居左对齐, 点击居中对齐后, 居中对齐的图标没有被点亮, 失去焦点后图标才被点亮.

**Comment by zuohuadong** [comment]
https://neditor.notadd.com/demo/  demo测试中无此BUG

**Comment by LitoMore** [comment]
@ucando 
1. 首先确认是不是你自己的其他的 js 或 css 文件影响了 neditor 的样式
2. 请告知你所使用浏览器的版本信息
