### ISSUE TITLE
插入地图有问题

### ISSUE THREAD

**Issue by yuyeqianxun** [notadd/neditor#21]
我尝试了你的线上demo，百度原版的线上demo，以及我自己部署的demo，发现三个地方中：百度的能插入静态地图，neditor无法插入静态地图。动态地图都插入不了。我猜测是不是由于百度现在使用地图需要开发者秘钥的原因？如果是这个原因的话麻烦加个配置的接口吧，不然得手动添加，或者别人不知道以为是bug？

**Comment by zuohuadong** [comment]
https 必须用到新版的接口，但是貌似百度没有公共秘钥

**Comment by DengMingHao** [comment]
静态地图无法插入的原因，我自己检查后。发现是因为HTML代码格式有问题，只需要修改 ueditor/dialogs/map/map.html  下 151 行处。
`
editor.execCommand('inserthtml', '<img width="'+ size.width +'"height="'+ size.height +'" src="' + url + '"' + (styleStr ? ' style="' + styleStr + '"' :'') + '/>');
`
修改为 ↓
`
editor.execCommand('inserthtml', '<img width="'+ size.width +'" height="'+ size.height +'" src="' + url + '"' + (styleStr ? ' style="' + styleStr + '"' :'') + '/>');
`
在 height 前面加上一个空格即可。
