### ISSUE TITLE
你好，请问这是一个bug吗？

### ISSUE THREAD

**Issue by cj-cp3** [notadd/neditor#23]
我的问题是：

使用toobar 里的"simpleupload"上传图片之后，离开编辑器，然后再点击图片，就只会选中这个图片，无法进入编辑状态：

一开始正常上传：
![default](https://user-images.githubusercontent.com/33646419/33978243-c438b626-e0d9-11e7-8721-9148afeb75f3.png)

上传然后退出编辑再点击图片时就无法编辑了，无法回到编辑状态，只能删除图片
![default](https://user-images.githubusercontent.com/33646419/33978376-57672fea-e0da-11e7-8311-91d84a397a92.png)

另外，我测试了设置editor高度为可变结果也是一样的，不能点击图片，否则无法再进入编辑状态。。。。。。。能不能看下呢，谢谢了。。。

**Comment by zuohuadong** [comment]
F12  也没有什么报错么

**Comment by cj-cp3** [comment]
@zuohuadong 
感谢回复！初始引入时有一个错误：
TypeError: node is undefined
不过上传图片的时候没什么变化，没有得到新错误信息..你这里有没有在线demo可以测试下呢？

另外，能不能设置图片为不可点击状态，只需要在neditor里编辑就ok了..

**Comment by cj-cp3** [comment]
问题解决了,是因为默认设置编辑器里image 可以自动拉伸，所以导致每次都可以点击这个图片，在neditor.config.js里把    //启用图片拉伸缩放更改成,imageScaleEnabled: false 就ok啦

还是谢谢了，真是不好意思，自己没研究懂就来问了，Sorry。。。。
谢谢了
