### ISSUE TITLE
致命问题

### ISSUE THREAD

**Issue by henryatman** [notadd/neditor#28]
致命问题

系统环境， mac，
浏览器 chrome，
demo地址：https://demo.neditor.notadd.com/

问题描述：

鼠标移动到图标上（工具栏上）无提示，查看dom里的确title还在，但是不提示了，应该是改svg的问题

百度官网的demo没这个问题，这个问题导致几乎要都点一遍才知道是什么功能，

严重妨碍使用，望修复

**Comment by henryatman** [comment]
btw，为什么不直接用 http://fontawesome.io/icons/ 来做呢，简洁易用，还能同步升级

**Comment by zuohuadong** [comment]
样式不适合。。。

**Comment by zuohuadong** [comment]
title 确实是问题，后期版本会修复。
但是没说的那么严重，常用的功能:比如加粗， 一定是B 图标。
