### ISSUE TITLE
图片选中的问题

### ISSUE THREAD

**Issue by qinggan** [notadd/neditor#30]
图片编辑是一个很大的问题，特别是当我使用了固定高度后，选中图片就坑爹的出现截图的问题。如果禁用掉或是修正。
![20180107-170509](https://user-images.githubusercontent.com/9583951/34648608-330a438e-f3d7-11e7-9b7f-7f62acc8efea.jpg)

 此问题是在固定高度时出现的，补充下，在Neditor也一样有这个问题

![image](https://user-images.githubusercontent.com/9583951/34648631-d9d22588-f3d7-11e7-949c-965da3197d67.png)

**Comment by zuohuadong** [comment]
2.0新版发布，欢迎测试
