### ISSUE TITLE
nodejs版啥时候出

### ISSUE THREAD

**Issue by hongxiangWang** [notadd/neditor#31]
nodejs版啥时候出？等着用

**Comment by zhouzhangfan** [comment]
+1

**Comment by zuohuadong** [comment]
@hongxiangWang @zhouzhangfan 
团队对node 不太熟悉，预计这月底或下月初。
如果有能对 这个进行移植的，也欢迎给我们提交PR～
https://github.com/netpi/ueditor

**Comment by zuohuadong** [comment]
@sword913 目前正在做～

**Comment by yuu2lee4** [comment]
https://www.jianshu.com/p/341b66f99b62  看这个行不
https://www.npmjs.com/search?q=node%20ueditor&page=1&ranking=optimal

**Comment by avilang** [comment]
啥时候可以出啊，等着用~~不行就自己动手移值 [https://github.com/netpi/ueditor](https://github.com/netpi/ueditor)

**Comment by zuohuadong** [comment]
欢迎提交PR～
