### ISSUE TITLE
你好，请问如何修改，让上传的图片显示不要占满整个编辑器呢？

### ISSUE THREAD

**Issue by Cjlyn** [notadd/neditor#33]
请问在哪里修改呢？找了半天没找到

编辑器上传图片会占满100%的宽度，如何缩小？

**Comment by twilroad** [comment]
在图片属性编辑里面可以实现

**Comment by Cjlyn** [comment]
@twilroad  你好，能说具体点吗？谢谢了..

**Comment by JinXin1995** [comment]
编辑器的css里设置了图片的最大宽度是100%，所以如果你的图片比编辑器大的话就会占满编辑器，如果想修改最大宽度的话可以打开themes文件夹下的iframe.css文件，将 img 标签的max-width改成你想要的宽度
