### ISSUE TITLE
官方demo中，插入音频或视频，再点击html按钮，刚刚插入的内容就消失了

### ISSUE THREAD

**Issue by o0rid0o** [notadd/neditor#34]
访问咱们的官方DEMO
先搜索并插入一个音频，显示『音乐插入成功』
然后点击左上角的『html』按钮查看源码，发现没有音频的源码
然后再点击『html』，就会发现刚刚插入的音频，消失了

视频同样的效果

**Comment by qa2080639** [comment]
遇到了  其实就是没代码  提交内容也是没video标签的

**Comment by zuohuadong** [comment]
2.0 发布
