### ISSUE TITLE
.Net Core版本的后端文件上传服务

### ISSUE THREAD

**Issue by baiyunchen** [notadd/neditor#35]
NEditor的作者您好，

今天有人告知了我NEditor的存在，我的心情是万分激动的，之前一直觉得UEditor挺好，就是很多BUG，官方也不维护了，很高兴看到有个大牛能够继续维护这个宇宙第一富文本编辑器。

当然，这不是重点。

最近我为微软最新的跨平台技术.NET Core写了UEditor的后端文件上传相关服务的API，看起来也是能够无缝的对接到您的NEditor中的，希望您能够在项目的文档中，将我的项目地址做一个链接，以便帮助到更多的人。
项目地址：https://github.com/baiyunchen/UEditor.Core

再次感谢您的无私奉献！

**Comment by zuohuadong** [comment]
感谢支持，可以修改readme.md后提交PR，再次感谢。

**Comment by baiyunchen** [comment]
已提交，烦请merge https://github.com/notadd/neditor/pull/36

**Comment by baiyunchen** [comment]
第一次竟然写错链接地址了，已重新Merge https://github.com/notadd/neditor/pull/37
大家在使用的过程中，遇到任何问题，请在这里提交Issue,尽量在第一时间解决：https://github.com/baiyunchen/UEditor.Core/issues
