### ISSUE TITLE
在Firefox下关掉自动长高，滚动条达到一定高度点击Toolbars的功能，滚动条自动回到顶部了

### ISSUE THREAD

**Issue by logan303** [notadd/neditor#42]
关闭自动自动长高：
autoHeightEnabled:false
设置初始高度：
initialFrameHeight:400

这样的设置应该是内容超过400的高度自动出现滚动条，但是在Firefox 59.0.3版本下（其它版本没试），内容达到一定的高度（大概initialFrameHeight设置的高两倍），再点击上工具条的功能滚动条就自动回到了顶部了。Chrome则不会有这样的现象。

不知道有没有朋友也遇到这样的问题

**Comment by zuohuadong** [comment]
这块确实有不少BUG，如果有修复，欢迎提交PR
