### ISSUE TITLE
复制粘贴的HTML富文本，元素会被自动添加 style标签 ，怎么不默认添加？

### ISSUE THREAD

**Issue by mifunc** [notadd/neditor#43]
研究了几天 neditor ,发现粘贴的HTML富文本，会自动加上 style属性，看了代码，没发现在哪去掉，请求指导，谢谢。
![image](https://user-images.githubusercontent.com/14819748/41275701-4f86ae10-6e54-11e8-9792-8b1708a8f9af.png)

**Comment by twilroad** [comment]
应该是从paste想关的command里面做到插入，需要追踪paste命令的执行才能调整，或者直接全局搜索相关代码
