### ISSUE TITLE
自定义工具栏按钮无法显示

### ISSUE THREAD

**Issue by herojhc** [notadd/neditor#44]
自定义按钮支持吗？ 我试了一下 按照原版 Ueditor 添加自定义按钮 可以显示，但是 按照 Neditor 则不显示，是什么原因？

**Comment by zuohuadong** [comment]
Neditor 的所有图标均使用 SVG，跟原版有不兼容的地方。
目前暂无支持自定义按钮的计划，但欢迎提交PR
