### ISSUE TITLE
背景：在线图片无反应

### ISSUE THREAD

**Issue by zuohuadong** [notadd/neditor#55]
![image](https://user-images.githubusercontent.com/11203929/44199411-a1595800-a176-11e8-9fe5-bdc1ebdcf2d7.png)
点击在线图片：
![image](https://user-images.githubusercontent.com/11203929/44199421-ac13ed00-a176-11e8-9594-7fc483c988b3.png)

**Comment by Tian-Hun** [comment]
编辑器中所有在线图片暂时屏蔽
