### ISSUE TITLE
nothing

### ISSUE THREAD

**Issue by hiliyi** [notadd/neditor#59]
无所谓了。

**Comment by zuohuadong** [comment]
抱歉，最近团队项目一直比较忙，抽时间完善项目，目前大概10-30天一次版本迭代。
此项目并不是商业项目，目的一是为了我们内部使用，二也是为了给一些人提供方便。
另外也是因为百度 ueditor 不更新，想提供一个新的平台， 大家可以提交 PR 共享劳动成果。
没必要玻璃心，没人天生就欠你的。
祝好～
