### ISSUE TITLE
撤销报错

### ISSUE THREAD

**Issue by leehavin** [notadd/neditor#62]
The given range isn't in document.

**Comment by zuohuadong** [comment]
能具体下，具体是什么操作呢？
我这无法复现

**Comment by leehavin** [comment]
![menu saveimg savepath20181018164856](https://user-images.githubusercontent.com/12468518/47142570-bd53b400-d2f5-11e8-93a8-43f96a89c26c.jpg)

Console Error：The given range isn't in document.

Sorry,No images were uploaded for the first time,UEditor also reported an error

**Comment by zuohuadong** [comment]
请先配置 config
