### ISSUE TITLE
插入图片后，粘贴其他内容后，插入的图片变为加载小图标

### ISSUE THREAD

**Issue by sangbobo** [notadd/neditor#64]
环境：windows系统，chrome浏览器
本地有bug，发现官网的demo也有此bug
步骤1：
![image](https://user-images.githubusercontent.com/5309706/46058572-401d9f00-c18e-11e8-9777-aa40333d086e.png)
步骤2：
![image](https://user-images.githubusercontent.com/5309706/46058607-68a59900-c18e-11e8-87f7-3938a40eaee0.png)
步骤3：拷贝图片，粘贴图片
![image](https://user-images.githubusercontent.com/5309706/46058623-78bd7880-c18e-11e8-9148-f5888363136c.png)
其他：粘贴文本也会导致插入的图片发生问题
![image](https://user-images.githubusercontent.com/5309706/46058635-81ae4a00-c18e-11e8-82b9-eccbcde19677.png)

**Comment by zuohuadong** [comment]
请先配置 上传 service ，官网demo 也没配置。

**Comment by zuohuadong** [comment]
请先配置 上传 service ，不然不论是插入在线图片还是本地 都会有此问题

**Comment by sangbobo** [comment]
我在本地配置 service 了，上传到七牛后，富文本正常显示图片，图片地址也没错。但是一粘贴文本到富文本，图片就变成加载状态了。

**Comment by sangbobo** [comment]
> 请先配置上传服务，不然不论是插入在线图片还是本地都会有此问题



> 请先配置上传服务，不然不论是插入在线图片还是本地都会有此问题

我在本地配置 service 了，上传到七牛后，富文本正常显示图片，图片地址也没错。但是一粘贴文本到富文本，图片就变成加载状态了。

**Comment by sangbobo** [comment]
> > 请先配置 上传 service ，不然不论是插入在线图片还是本地 都会有此问题
> 
> 我在本地配置 service 了，上传到七牛后，富文本正常显示图片，图片地址也没错。但是一粘贴文本到富文本，图片就变成加载状态了。

看了下源码，解决了，好像是因为    设置远程图片是否抓取到本地保存   引起的问题
设置catchRemoteImageEnable 为  false 就解决了。

而 config.js中默认注释了此项。
