### ISSUE TITLE
微信公众号粘贴过来，图片大小不对

### ISSUE THREAD

**Issue by zhfish** [notadd/neditor#65]
随便举个例子
`https://mp.weixin.qq.com/s?src=11&timestamp=1539226807&ver=1175&signature=TmeYzn1ejdKyNLlIp3nlz5Ptko7IPlBcqW*K1YjMB89m0IJPXhKrNcpBiU-dPLEaJqm*vei*4SM*ZJUrSIKj7jvY-c9nfnTD989Fuwr*tt3Q3cWgUycPNHK07-TyK6xE&new=1`  
复制粘贴，正文  
在ueditor里，样式不变  
在neditor里，图片变的非常非常小

**Comment by zuohuadong** [comment]
配置好上传配置， 再试下~ 

neditor 把后端部分的东西剥离了，需要配置上传接口才正常

**Comment by zhfish** [comment]
可以不上传么？ 想盗图。。。

**Comment by zuohuadong** [comment]
那个别想了，有防盗链机制的，你本地图片缓存过期了，图片就无效了～
