### ISSUE TITLE
如何精简体积

### ISSUE THREAD

**Issue by catch6** [notadd/neditor#70]
看了官方的这个包，感觉实在是太大了，很多功能根本用不到，怎么去除掉来精简体积，一个页面加载个几M的js。css等资源实在有点大

**Comment by zuohuadong** [comment]
我们目前的办法也是把资源放在CDN上，后面会考虑在线定制。

**Comment by zuohuadong** [comment]
https://github.com/notadd/neditor/issues/81

关于自定义图标，已经开放 svg 集合文件

**Comment by zuohuadong** [comment]
超过30天无回复，暂时关闭。 如有问题可继续回复
