### ISSUE TITLE
ISSUE_TEMPLATE 中文档已经404

### ISSUE THREAD

**Issue by picasso250** [notadd/neditor#74]
>* 提 `ISSUE` 之前，**请先看看文档**。传送门：[文档](http://fex.baidu.com/neditor/)。很多问题，在文档中都能有答案。特别是配置之类的。

文档链接：
http://fex.baidu.com/neditor/
已经404

**Comment by zuohuadong** [comment]
http://fex.baidu.com/ueditor/
