### ISSUE TITLE
关于火狐兼容问题

### ISSUE THREAD

**Issue by dxcswl** [notadd/neditor#76]
当页面出现滚动  编辑器种也有滚动时候 
火狐会出现大段的空白   
<div id="edui1" class="edui-editor  edui-notadd" style="z-index: 1100;">
下面生成一个很高的高度
<div style="height: 12068px;"></div>

只是在火狐

**Comment by zuohuadong** [comment]
chrome 正常么？ 
firefox 有没有报错之类的，版本是多少

**Comment by dxcswl** [comment]
只有火狐出现
火狐的警告：
     此网站似乎使用 scroll-linked 定位效果。这可能无法与异步平移一起使用；参见 https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects 详细了解，也可加入我们一起讨论相关的工具和功能！

火狐版本：63.0.3 (64 位)

**Comment by zuohuadong** [comment]
@dxcswl  可能要到下个月才有时间，如果你能修复此问题的话，欢迎提交PR
