### ISSUE TITLE
插入视频回显时中间视频图标丢失

### ISSUE THREAD

**Issue by Skqing** [notadd/neditor#78]
插入视频时回显是正常的，中间带有视频图标，如图：
![image](https://user-images.githubusercontent.com/1713001/49208029-9b1f7c80-f3f1-11e8-91b5-aa163c36fe59.png)

编辑页面把值重新用setContent设置到编辑器里，结果中间视频图标不显示，调试看生成的代码是这样的：
```
"<img  width="420" height="280" _url="http://player.youku.com/player.php/sid/XMzgzOTgyMzc4MA==/v.swf" class="edui-faked-video" src="http://localhost:8282/static/plugins/Neditor-2.1.6/themes/notadd/images/spacer.gif" style="background:url(http://localhost:8282/static/plugins/Neditor-2.1.6/themes/notadd/images/videologo.gif) no-repeat center center; border:1px solid gray;" data-ad="1234567890"/>"
```
但是检查HTML属性结果却是：
![image](https://user-images.githubusercontent.com/1713001/49207989-7deaae00-f3f1-11e8-94b0-2b29a9017b26.png)
style属性没了，请问是啥原因？

**Comment by Skqing** [comment]
查到了是调用了
`
  me.addInputRule(function(root) {
    switchImgAndVideo(root);
  });
`
`switchImgAndVideo这个方法做了`node.parentNode.replaceChild(UE.uNode.createElement(html), node);`这个操作，导致元素替换的时候style丢失了吧。
不理解的是为什么要switchImgAndVideo(root);，为什么不让回显视频呢，我把这个注释掉，优酷视频在编辑器里都能回显了。

**Comment by Skqing** [comment]
`
  me.addOutputRule(function(root) {
    switchImgAndVideo(root, true);
  });
  me.addInputRule(function(root) {
    switchImgAndVideo(root);
  });
`
写这几行代码的目的是干啥呢？

**Comment by zuohuadong** [comment]
我记得这个是把视频替换成图片。

正常行为应该是在编辑时不回显。
在发布时（生成代码）时回显。

Ueditor 遗留问题比较多，目前对此项目只能慢慢做修改了。

**Comment by zuohuadong** [comment]
超过30天无回复，暂时关闭 issues
