### ISSUE TITLE
缩进与行高问题，已经重新配图详细说明问题，麻烦有空查看和修复，谢谢！

### ISSUE THREAD

**Issue by jackyGang** [notadd/neditor#89]
paragraph.js文件中的domUtils.remove(para.parentNode, true);改为domUtils.remove(para, true);
`            //trace:1706 选择的就是h1-6要删除
            if (
              attrs &&
              /h\d/i.test(parent.tagName) &&
              !/h\d/i.test(para.tagName)
            ) {
              domUtils.setAttributes(parent, attrs);
              if (
                sourceCmdName &&
                sourceCmdName == "customstyle" &&
                attrs.style
              ) {
                parent.style.cssText = attrs.style;
              }
              domUtils.remove(para, true);
              para = parent;
            } else {
              domUtils.remove(para.parentNode, true);
            }
          }`

**Comment by zuohuadong** [comment]
![image](https://user-images.githubusercontent.com/11203929/49425957-eb278600-f7d9-11e8-96b3-ebfed2289b2e.png)

![image](https://user-images.githubusercontent.com/11203929/49425960-f11d6700-f7d9-11e8-94e8-bb80e23de582.png)


不知道你所指的是什么？

目前是基于  ueditor 1.5 演变而来的

**Comment by jackyGang** [comment]
![default](https://user-images.githubusercontent.com/13132751/49575879-c6b8de80-f97e-11e8-8aec-59a00fcc098e.gif)

**Comment by zuohuadong** [comment]
方便提交个PR 么
