### ISSUE TITLE
关于使用vue集成作者的Neditor图片上传产生的问题

### ISSUE THREAD

**Issue by surick** [notadd/neditor#90]
图片上传，选完图片点击上传的时候总报错：editor.getOpt(...) is not a function，是配置问题还是不支持vue？

**Comment by zuohuadong** [comment]
有具体项目地址么？

2.x 以后删除了后端代码，需要配置 service

**Comment by surick** [comment]
[项目](https://github.com/moneyinto/vue-layui)
已经被老大解决了，😆

**Comment by L1nYong** [comment]
老哥，这问题咋解决的，我也碰到了
