### ISSUE TITLE
涂鸦上传成功后显示undefined

### ISSUE THREAD

**Issue by wuhanligong110** [notadd/neditor#98]
![image](https://user-images.githubusercontent.com/5670107/49988416-917d4380-ffb1-11e8-8329-f32d030b1b3a.png)

对应的service.js

/**
 * 涂鸦上传service
 * @param {Object} context scrawlObj对象
 * @param {Object} editor  编辑器对象
 * @returns scrawlUploadService 对象
 */
window.UEDITOR_CONFIG['scrawlUploadService'] = function(context, editor) {
    return scrawlUploadService = {
        /**
         * 点击涂鸦模态框确认按钮时触发
         * 上传涂鸦图片
         * @param {Object} file 涂鸦canvas生成的图片
         * @param {Object} base64 涂鸦canvas生成的base64
         * @param {Function} success 上传成功回调函数,回传上传成功的response对象
         * @param {Function} fail 上传失败回调函数,回传上传失败的response对象
         */

        /**
         * 上传成功的response对象必须为以下两个属性赋值
         * 
         * 上传接口返回的response成功状态条件 {Boolean} (比如: res.code == 200)
         * res.responseSuccess = res.code == 200;
         * 
         * 指定上传接口返回的response中涂鸦图片路径的字段，默认为 url 
         * res.videoSrcField = 'url';
         */
        uploadScraw: function(file, base64, success, fail) {

            /* 模拟上传操作 */
            var formData = new FormData();
            formData.append('file', file, file.name);
			
			

            $.ajax({
                url: 'http://10.16.0.113:7777/',
                type: 'POST',
                data: formData,
				async: true,
				cache: false,
				contentType: false,
				processData: false
            }).done(function(res) {
                
				if(res.indexOf("MD5")!=-1){
					var result = res.substr(res.indexOf("MD5:") + 5, 32);
					var url = 'http://10.16.0.113:7777/'+result;
					console.log(url);
					res.url = url;
					res.responseSuccess = true;
					res.code = 200;
				}
				else{
					res.responseSuccess = false;
					console.log("upload fail.");
				}
                
                /* 上传接口返回的response成功状态条件 (比如: res.code == 200) */
                // res.responseSuccess = res.code == 200;

                /* 指定上传接口返回的response中涂鸦图片路径的字段，默认为 url 
                 * 如果涂鸦图片路径字段不是res的属性，可以写成 对象.属性 的方式，例如：data.url
                 */
                res.scrawlSrcField = 'url';

                /* 上传成功 */
                success.call(context, res);
            }).fail(function(err) {
                /* 上传失败 */
                fail.call(context, err);
            });
        }
    }
}

**Comment by zuohuadong** [comment]
这个我抽时间复现下

**Comment by wuhanligong110** [comment]
不好意思打扰了，已经解决了。zimg返回res是个字符串，所以加那些属性scrawlSrcField、url 等时并没有什么用。

**Comment by wuhanligong110** [comment]
> 这个我抽时间复现下

不好意思打扰了，已经解决了。zimg返回res是个字符串，所以加那些属性scrawlSrcField、url 等时并没有什么用。
